<a href="https://colab.research.google.com/github/prathibhavadlamudi/python.py/blob/main/16355558(PDS-Assignment2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 2 - 16355558

a, Look for the missing values in all the columns and either impute them (replace with mean,
median, or mode) or drop them. Justify your action for this task.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
# Drop 'New_Price' due to excessive missing values
df.drop('New_Price', axis=1, inplace=True)

In [4]:
df.dropna(inplace=True)

In [5]:
print("Remaining missing values:\n", df.isnull().sum())

Remaining missing values:
 Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

b, Remove the units from some of the attributes and only keep the numerical values (for
example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from
“New_price”).

In [8]:
df['Mileage'] = df['Mileage'].str.replace(r'\s+[a-zA-Z/]+', '', regex=True)
df['Engine'] = df['Engine'].str.replace(r'\s+CC', '', regex=True)
df['Power'] = df['Power'].str.replace(r'\s+bhp', '', regex=True)

In [9]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461,63.1,5.0,3.50

In [11]:
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')
df['Engine'] = pd.to_numeric(df['Engine'], errors='coerce')
df['Power'] = pd.to_numeric(df['Power'], errors='coerce')

df['Mileage'].fillna(df['Mileage'].median(),inplace=True)
df['Engine'].fillna(df['Engine'].median(),inplace=True)
df['Power'].fillna(df['Power'].median(),inplace=True)

<ipython-input-11-d0a234a6d2b3>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Mileage'].fillna(df['Mileage'].median(),inplace=True)
<ipython-input-11-d0a234a6d2b3>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Engine'].fillna(df['Engine'].median(),inplace=True)
<ipython-input-11-d0a234a6d2b3>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Power'].fillna(df['Power'].median(),inplace=True)

In [12]:
print(df.isnull().sum())

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

c,  Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot
encoded value.

In [13]:
fuel_mapping = {'Diesel': 0, 'Petrol': 1, 'Electric': 2}
df['Fuel_Type'] = df['Fuel_Type'].replace(fuel_mapping)

transmission_mapping = {'Manual': 0, 'Automatic': 1}
df['Transmission'] = df['Transmission'].replace(transmission_mapping)

<ipython-input-13-d8bfb74525b2>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Fuel_Type'] = df['Fuel_Type'].replace(fuel_mapping)
<ipython-input-13-d8bfb74525b2>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Transmission'] = df['Transmission'].replace(transmission_mapping)

In [14]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.20,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199,88.70,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968,140.80,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.10,5.0,3.50

d, Create one more feature and add this column to the dataset (you can use mutate function in
R for this). For example, you can calculate the current age of the car by subtracting “Year” value
from the current year.

In [15]:
from datetime import datetime
current_year = datetime.now().year

df['Car_Age'] = current_year - df['Year']

In [16]:
print(df[['Year', 'Car_Age']].head())

   Year  Car_Age
0  2015       10
1  2011       14
2  2012       13
3  2013       12
4  2013       12

e, Perform select, filter, rename, mutate, arrange and summarize with group by operations (or
their equivalent operations in python) on this dataset.

In [17]:
# select
required_columns = ['Name', 'Mileage', 'Engine', 'Seats']
df_selected = df[required_columns]
df_selected.head()

                               Name  Mileage  Engine  Seats
0  Hyundai Creta 1.6 CRDi SX Option    19.67    1582    5.0
1                      Honda Jazz V    13.00    1199    5.0
2                 Maruti Ertiga VDI    20.77    1248    7.0
3   Audi A4 New 2.0 TDI Multitronic    15.20    1968    5.0
4            Nissan Micra Diesel XV    23.08    1461    5.0

In [18]:
#filter
filtered_df = df[(df['Mileage'].astype(float) > 20) & (df['Engine'].astype(float) < 1500)]
filtered_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_Age
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,13
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.10,5.0,3.50,12
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,0,0,Second,22.30,1248,74.00,5.0,1.95,13
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,1,0,First,21.56,1462,103.25,5.0,9.95,7
10,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,0,0,First,25.20,1248,74.00,5.0,5.60,10

In [19]:
#rename
renamed_df = df.rename(columns={'Power_per_Liter': 'Power_per_Fuel'})
renamed_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.20,5.0,12.50,10
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199,88.70,5.0,4.50,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968,140.80,5.0,17.74,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.10,5.0,3.50,12

In [24]:
#arrange
sorted_df = df.sort_values(by=['Car_Age', 'Mileage'], ascending=[True, False])
sorted_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_Age
4198,4328,Maruti Swift DDiS VDI,Coimbatore,2019,41075,0,0,First,28.40,1248,74.0,5.0,8.40,6
984,1018,Maruti Swift Dzire VDI Optional,Kochi,2019,18592,0,0,First,26.59,1248,74.0,5.0,8.51,6
4267,4399,Maruti Swift Dzire AMT ZDI,Chennai,2019,65000,0,1,First,26.59,1248,74.0,5.0,6.75,6
5405,5560,Renault KWID RXT Optional,Kochi,2019,6568,1,0,First,25.17,799,53.3,5.0,5.09,6
5628,5789,Renault KWID RXL,Kochi,2019,7858,1,0,First,25.17,799,53.3,5.0,3.80,6

In [22]:
#summarize
grouped_df = df.groupby('Fuel_Type').agg({'Mileage': 'mean'}).sort_values(by='Mileage', ascending=False)
grouped_df.head()

             Mileage
Fuel_Type
0          18.670165
1          17.650942

In [26]:
summary_csv_file = 'train.csv'
grouped_df.to_csv(summary_csv_file, index=False)